import type { FlowActor, FlowStep, Protocol } from "./protocols";

const standardActors: FlowActor[] = [
  { id: "user", name: "Operator", detail: "Resource Owner" },
  { id: "client", name: "Client", detail: "Application" },
  { id: "auth", name: "Authorization", detail: "Token Service" },
  { id: "api", name: "Resource", detail: "Protected API" },
];

const fidoActors: FlowActor[] = [
  { id: "user", name: "User", detail: "Authorization Gesture" },
  { id: "client", name: "Browser", detail: "WebAuthn Client" },
  { id: "auth", name: "Authenticator", detail: "Platform / Roaming" },
  { id: "api", name: "Relying Party", detail: "Application Server" },
];

const protocol = (
  value: Omit<Protocol, "actors" | "highlights"> & {
    actors?: FlowActor[];
    highlights: [string, string][];
  },
): Protocol => ({
  ...value,
  actors: value.actors ?? standardActors,
  highlights: value.highlights.map(([label, result]) => ({ label, value: result })),
});

const step = (
  from: string,
  to: string,
  label: string,
  detail: string,
  security: string,
  message: string,
): FlowStep => ({ from, to, label, detail, security, message });

export const additionalProtocols: Protocol[] = [
  protocol({
    slug: "oauth-2-0-client-credentials",
    shortName: "Client Credentials",
    title: "Client Credentials Flow",
    eyebrow: "OAuth 2.0 / Machine-to-Machine",
    summary:
      "ユーザーを介さず、クライアント自身の権限でサービス間APIへアクセスするM2M向けフローです。",
    accent: "violet",
    family: "OAuth 2.0",
    status: "specialized",
    highlights: [
      ["Actor", "Machine"],
      ["Grant", "client_credentials"],
      ["User", "Not involved"],
    ],
    steps: [
      step(
        "user",
        "client",
        "バッチ処理を起動",
        "運用処理やバックエンドジョブがAPIアクセスを必要とします。",
        "ユーザーの代理ではなくクライアント自身として動作します。",
        "scheduler → start job",
      ),
      step(
        "client",
        "auth",
        "クライアントを認証",
        "client_idとclient_secretなどを使ってトークンを要求します。",
        "資格情報はバックエンドだけに保存し、ブラウザへ置きません。",
        "POST /oauth2/token  grant_type=client_credentials",
      ),
      step(
        "auth",
        "auth",
        "権限を評価",
        "登録済みクライアントと許可scopeを確認します。",
        "要求scopeをクライアントに事前許可した範囲へ制限します。",
        "authenticate(client) → resolve scopes",
      ),
      step(
        "auth",
        "client",
        "トークンを発行",
        "クライアントを主体とするアクセストークンを返します。",
        "短い有効期限を使い、不要なrefresh tokenは発行しません。",
        "200 { access_token, expires_in }",
      ),
      step(
        "client",
        "api",
        "サービス間APIを呼ぶ",
        "Bearerトークンで保護APIへアクセスします。",
        "APIはaudienceとscopeに加えクライアント主体を確認します。",
        "POST /api/jobs  Authorization: Bearer ...",
      ),
    ],
  }),
  protocol({
    slug: "oauth-2-0-device-authorization",
    shortName: "Device Authorization",
    title: "Device Authorization Grant",
    eyebrow: "RFC 8628 / Input-Constrained Devices",
    summary: "テレビやCLIなど入力制約のある端末を、別のブラウザを使って安全に認可するフローです。",
    accent: "violet",
    family: "OAuth 2.0",
    status: "specialized",
    highlights: [
      ["Device", "TV / CLI"],
      ["Proof", "User code"],
      ["Channel", "Secondary browser"],
    ],
    steps: [
      step(
        "client",
        "auth",
        "デバイスコードを要求",
        "端末がclient_idとscopeをDevice Authorization Endpointへ送ります。",
        "公開クライアントとして秘密情報を端末へ埋め込みません。",
        "POST /oauth2/device_authorization",
      ),
      step(
        "auth",
        "client",
        "コードとURLを返却",
        "device_code、user_code、verification_uri、intervalを返します。",
        "user_codeは短く入力可能、device_codeは高エントロピーにします。",
        "200 { device_code, user_code, verification_uri }",
      ),
      step(
        "client",
        "user",
        "別端末での操作を案内",
        "画面に確認URLとuser_code、またはQRコードを表示します。",
        "QRコードに秘密のdevice_codeを直接含めない設計を推奨します。",
        "Open verification_uri and enter WDJB-MJHT",
      ),
      step(
        "user",
        "auth",
        "ログインして認可",
        "ユーザーがスマートフォン等でログインし、対象端末を承認します。",
        "表示された端末情報と要求scopeを確認します。",
        "Authenticate → enter user_code → approve",
      ),
      step(
        "client",
        "auth",
        "トークンをポーリング",
        "端末が指定intervalを守ってToken Endpointをポーリングします。",
        "slow_down応答時は間隔を延長し、期限切れで停止します。",
        "POST /oauth2/token  grant_type=device_code",
      ),
      step(
        "auth",
        "client",
        "トークンを発行",
        "ユーザー承認後にアクセストークンを返します。",
        "device_codeは一度だけ利用可能にします。",
        "200 { access_token, refresh_token }",
      ),
      step(
        "client",
        "api",
        "保護APIへアクセス",
        "端末が認可されたscope内でAPIを利用します。",
        "端末紛失時にセッションを取り消せる管理機能を用意します。",
        "GET /api/content  Authorization: Bearer ...",
      ),
    ],
  }),
  protocol({
    slug: "oauth-2-0-refresh-token",
    shortName: "Refresh Token",
    title: "Refresh Token Flow",
    eyebrow: "OAuth 2.0 / Token Lifecycle",
    summary:
      "アクセストークンの期限切れ後、ユーザーを再認証させずに新しいトークンを取得する継続セッションのフローです。",
    accent: "violet",
    family: "OAuth 2.0",
    status: "recommended",
    highlights: [
      ["Purpose", "Renew access"],
      ["Rotation", "Recommended"],
      ["Channel", "Back-channel"],
    ],
    steps: [
      step(
        "client",
        "api",
        "期限切れを検知",
        "API応答またはexp claimからアクセストークンの期限切れを検知します。",
        "期限切れトークンを繰り返し送信しません。",
        "401 invalid_token",
      ),
      step(
        "client",
        "auth",
        "更新を要求",
        "refresh_tokenをToken Endpointへバックチャネル送信します。",
        "refresh tokenはブラウザから読めない安全な領域へ保存します。",
        "POST /oauth2/token  grant_type=refresh_token",
      ),
      step(
        "auth",
        "auth",
        "状態と権限を再評価",
        "失効、有効期限、クライアント、scopeを確認します。",
        "セッション無効化や権限変更を更新時に反映します。",
        "validate(refresh_token, client, scopes)",
      ),
      step(
        "auth",
        "client",
        "トークンをローテーション",
        "新しいaccess tokenと必要に応じ新しいrefresh tokenを返します。",
        "古いrefresh tokenを無効化し、再利用検知時は系列全体を失効します。",
        "200 { access_token, refresh_token }",
      ),
      step(
        "client",
        "api",
        "API呼び出しを再開",
        "新しいaccess tokenを使って処理を継続します。",
        "失敗時は無限更新せず、ユーザーへ再認証を要求します。",
        "GET /api/profile  Authorization: Bearer new-token",
      ),
    ],
  }),
  protocol({
    slug: "oauth-2-0-implicit",
    shortName: "Implicit (Legacy)",
    title: "Implicit Grant — Legacy",
    eyebrow: "OAuth 2.0 / Deprecated Browser Flow",
    summary:
      "アクセストークンをフロントチャネルで直接返す旧方式です。現代のアプリではAuthorization Code + PKCEを使用します。",
    accent: "violet",
    family: "OAuth 2.0",
    status: "legacy",
    highlights: [
      ["Status", "Do not use"],
      ["Response", "token"],
      ["Replacement", "Code + PKCE"],
    ],
    steps: [
      step(
        "user",
        "client",
        "ログイン開始",
        "ブラウザアプリが認可を開始します。",
        "このフローは歴史理解のための説明です。新規採用しません。",
        "GET /login",
      ),
      step(
        "client",
        "auth",
        "tokenを直接要求",
        "response_type=tokenで認可エンドポイントへ遷移します。",
        "PKCEによるコード交換保護を利用できません。",
        "GET /authorize?response_type=token",
      ),
      step(
        "user",
        "auth",
        "ログインして同意",
        "ユーザーがAuthorization Serverでログインし、scopeへの同意を行います。",
        "認証画面自体はAuthorization Serverが提供します。",
        "Authenticate → consent",
      ),
      step(
        "auth",
        "client",
        "フラグメントで返却",
        "アクセストークンをURL fragmentへ直接含めます。",
        "履歴、拡張機能、参照元などへの漏えいリスクがあります。",
        "302 /callback#access_token=...",
      ),
      step(
        "client",
        "api",
        "ブラウザからAPIを呼ぶ",
        "JavaScriptがトークンを読みBearerとして送ります。",
        "XSSがトークン窃取へ直結するためCode + PKCEへ移行します。",
        "GET /api/profile  Authorization: Bearer ...",
      ),
    ],
  }),
  protocol({
    slug: "oauth-2-0-password",
    shortName: "Password (Legacy)",
    title: "Resource Owner Password Grant — Legacy",
    eyebrow: "OAuth 2.0 / Deprecated Password Grant",
    summary:
      "クライアントがユーザーのパスワードを直接収集する旧方式です。OAuth 2.1では削除され、新規利用できません。",
    accent: "violet",
    family: "OAuth 2.0",
    status: "legacy",
    highlights: [
      ["Status", "Removed in 2.1"],
      ["Risk", "Password exposure"],
      ["Replacement", "Code + PKCE"],
    ],
    steps: [
      step(
        "user",
        "client",
        "資格情報を入力",
        "ユーザーがクライアント自身の画面へIDとパスワードを入力します。",
        "第三者クライアントへ資格情報を渡す設計自体が問題です。",
        "username + password",
      ),
      step(
        "client",
        "auth",
        "パスワードを転送",
        "grant_type=passwordと資格情報をToken Endpointへ送ります。",
        "フィッシング耐性やMFA、IdP選択を損ないます。",
        "POST /token  grant_type=password&username=...",
      ),
      step(
        "auth",
        "auth",
        "資格情報を検証",
        "Authorization Serverがユーザー名とパスワードを検証します。",
        "クライアントのログやメモリにもパスワードが残る恐れがあります。",
        "verify(username, password)",
      ),
      step(
        "auth",
        "client",
        "トークンを発行",
        "認証成功後にアクセストークンを返します。",
        "既存実装はAuthorization Code + PKCEへ移行します。",
        "200 { access_token }",
      ),
      step(
        "client",
        "api",
        "APIへアクセス",
        "取得したトークンでResource Serverを呼びます。",
        "この図は移行判断のためのLegacy資料です。",
        "GET /api/profile  Authorization: Bearer ...",
      ),
    ],
  }),
  protocol({
    slug: "oidc-hybrid",
    shortName: "OIDC Hybrid",
    title: "OpenID Connect Hybrid Flow",
    eyebrow: "OIDC Core 1.0 / Hybrid Flow",
    summary:
      "Authorization Endpointからcodeと一部トークンを組み合わせて返し、フロントチャネルとバックチャネルを併用する高度なOIDCフローです。",
    accent: "cyan",
    family: "FIDO2",
    status: "specialized",
    highlights: [
      ["Response", "code + id_token"],
      ["Validation", "c_hash"],
      ["Use case", "Specialized"],
    ],
    steps: [
      step(
        "user",
        "client",
        "サインイン開始",
        "クライアントがstateとnonceを生成します。",
        "必要性が明確な場合だけHybrid Flowを選択します。",
        "GET /login",
      ),
      step(
        "client",
        "auth",
        "複合レスポンスを要求",
        "response_type=code id_tokenなどを指定します。",
        "response_modeとredirect_uriを厳密に登録します。",
        "GET /authorize?response_type=code%20id_token&nonce=...",
      ),
      step(
        "user",
        "auth",
        "本人認証して同意",
        "ユーザーがOpenID Providerで本人認証し、claimsへの同意を行います。",
        "nonceを認証トランザクションへ関連付けます。",
        "Authenticate → consent",
      ),
      step(
        "auth",
        "client",
        "Clientへ戻る（code + ID Token）",
        "OpenID ProviderがcodeとID Tokenをリダイレクト応答へ入れ、ブラウザをClientへ戻します。",
        "ID Tokenの署名、nonce、c_hashを検証します。",
        "302 /callback#code=...&id_token=...",
      ),
      step(
        "client",
        "auth",
        "コードを交換",
        "バックチャネルでコードをトークンへ交換します。",
        "PKCEを併用しコード横取りを防ぎます。",
        "POST /token  code=...&code_verifier=...",
      ),
      step(
        "auth",
        "client",
        "完全なトークンセットを返却",
        "access tokenと必要なID tokenを返します。",
        "2つのID Tokenがある場合はsubなどの整合性を確認します。",
        "200 { access_token, id_token }",
      ),
      step(
        "client",
        "api",
        "UserInfoへアクセス",
        "アクセストークンで追加claimsを取得します。",
        "UserInfoのsubとID Tokenのsubを一致確認します。",
        "GET /userinfo  Authorization: Bearer ...",
      ),
    ],
  }),
  protocol({
    slug: "oidc-implicit",
    shortName: "OIDC Implicit (Legacy)",
    title: "OpenID Connect Implicit Flow — Legacy",
    eyebrow: "OIDC Core 1.0 / Legacy Front-channel Flow",
    summary:
      "IDトークンやアクセストークンをAuthorization Endpointから直接返す旧OIDCフローです。現在はCode + PKCEを優先します。",
    accent: "cyan",
    family: "FIDO2",
    status: "legacy",
    highlights: [
      ["Status", "Legacy"],
      ["Response", "id_token token"],
      ["Replacement", "Code + PKCE"],
    ],
    steps: [
      step(
        "user",
        "client",
        "サインイン開始",
        "ブラウザクライアントがnonceとstateを生成します。",
        "このフローは互換性理解のためにのみ説明します。",
        "GET /login",
      ),
      step(
        "client",
        "auth",
        "トークンを直接要求",
        "response_type=id_token tokenで認証を要求します。",
        "トークンがフロントチャネルを通過します。",
        "GET /authorize?response_type=id_token%20token",
      ),
      step(
        "user",
        "auth",
        "本人認証して同意",
        "ユーザーがOpenID Providerで本人認証と同意を行います。",
        "nonceを必ず発行し検証します。",
        "Authenticate → consent",
      ),
      step(
        "auth",
        "client",
        "Clientへ戻る（トークン）",
        "OpenID ProviderがURL fragmentへID TokenとAccess Tokenを入れ、ブラウザをClientへ戻します。",
        "URLやブラウザ環境からの漏えい面が大きくなります。",
        "302 /callback#id_token=...&access_token=...",
      ),
      step(
        "client",
        "client",
        "ID Tokenを検証",
        "署名、iss、aud、exp、nonce、at_hashを検証します。",
        "検証後もトークンを永続ストレージへ安易に保存しません。",
        "verify(id_token, nonce, at_hash)",
      ),
      step(
        "client",
        "api",
        "UserInfoへアクセス",
        "アクセストークンでclaimsを取得します。",
        "新規実装ではAuthorization Code + PKCEへ置き換えます。",
        "GET /userinfo  Authorization: Bearer ...",
      ),
    ],
  }),
  protocol({
    slug: "fido2-registration",
    shortName: "FIDO2 Registration",
    title: "FIDO2 / WebAuthn Registration Ceremony",
    eyebrow: "WebAuthn Level 3 / CTAP 2.2",
    summary:
      "Relying Party固有の公開鍵CredentialをAuthenticator内で生成し、公開鍵とAttestationをサーバーへ登録するフローです。",
    accent: "lime",
    family: "FIDO",
    status: "recommended",
    actors: fidoActors,
    highlights: [
      ["API", "credentials.create()"],
      ["Result", "Public key"],
      ["Secret", "Never leaves authenticator"],
    ],
    steps: [
      step(
        "user",
        "api",
        "登録を開始",
        "ログイン済みユーザーがPasskeyまたはSecurity Keyの登録を選択します。",
        "Credentialを追加する前に既存セッションを再確認します。",
        "POST /webauthn/registration/options",
      ),
      step(
        "api",
        "client",
        "作成Optionsを返却",
        "RP ID、user、challenge、pubKeyCredParamsなどを含む一回限りのOptionsを返します。",
        "challengeは暗号学的にランダムで短時間だけ有効にします。",
        "PublicKeyCredentialCreationOptions",
      ),
      step(
        "client",
        "auth",
        "Credential作成を要求",
        "ブラウザがAuthenticatorへmakeCredentialを要求します。外付けAuthenticatorではCTAP2を使用します。",
        "ブラウザがoriginとRP IDの関係を検証します。",
        "navigator.credentials.create({ publicKey }) → authenticatorMakeCredential",
      ),
      step(
        "auth",
        "user",
        "本人確認",
        "Authenticatorが生体認証、PIN、端末ロックなどでUser Verificationを行います。",
        "生体情報やPINはAuthenticator外へ送信しません。",
        "User presence / user verification",
      ),
      step(
        "auth",
        "auth",
        "鍵ペアを生成",
        "RP IDにスコープされた新しいCredential鍵ペアを生成します。",
        "秘密鍵はAuthenticator内に保持し、Relying Partyへ渡しません。",
        "generate(keyPair, credentialId, signCount)",
      ),
      step(
        "auth",
        "client",
        "Attestationを返却",
        "authenticatorData、clientDataJSON、attestationObjectをPublicKeyCredentialとして返します。",
        "challenge、origin、RP ID hashが署名対象に結び付きます。",
        "AuthenticatorAttestationResponse",
      ),
      step(
        "client",
        "api",
        "登録応答を送信",
        "ブラウザがCredential応答をRelying PartyへHTTPSで送信します。",
        "Base64url変換後もバイナリ内容を変更しません。",
        "POST /webauthn/registration/verify",
      ),
      step(
        "api",
        "api",
        "公開鍵を検証・保存",
        "challenge、origin、RP ID hash、flags、algorithm、attestationを検証して公開鍵を保存します。",
        "credentialId、publicKey、signCountをユーザーへ関連付けます。",
        "verify(attestation) → store(publicKey, credentialId)",
      ),
    ],
  }),
  protocol({
    slug: "fido2-authentication",
    shortName: "FIDO2 Authentication",
    title: "FIDO2 / WebAuthn Authentication Ceremony",
    eyebrow: "WebAuthn Level 3 / CTAP 2.2",
    summary:
      "AuthenticatorがRelying Partyのchallengeへ秘密鍵で署名し、パスワードを共有せずユーザーのCredential保有を証明するフローです。",
    accent: "lime",
    family: "FIDO",
    status: "recommended",
    actors: fidoActors,
    highlights: [
      ["API", "credentials.get()"],
      ["Proof", "Signed challenge"],
      ["Phishing", "Origin-bound"],
    ],
    steps: [
      step(
        "user",
        "api",
        "サインイン開始",
        "ユーザーがPasskeyによるサインインを開始します。Discoverable Credentialならユーザー名を省略できます。",
        "アカウント有無をOptions応答の違いから漏らさないようにします。",
        "POST /webauthn/authentication/options",
      ),
      step(
        "api",
        "client",
        "要求Optionsを返却",
        "challenge、rpId、allowCredentials、userVerificationなどを返します。",
        "challengeをセッションへ保存し、一度だけ検証します。",
        "PublicKeyCredentialRequestOptions",
      ),
      step(
        "client",
        "auth",
        "Assertionを要求",
        "ブラウザがAuthenticatorへCredentialの検索と署名を要求します。",
        "Authenticatorは要求元originに対応するRP IDのCredentialだけを使用します。",
        "navigator.credentials.get({ publicKey }) → authenticatorGetAssertion",
      ),
      step(
        "auth",
        "user",
        "本人確認",
        "ユーザーが生体認証、PIN、Security Keyのタッチなどを行います。",
        "User Verification要件をRPのポリシーに合わせます。",
        "User presence / user verification",
      ),
      step(
        "auth",
        "auth",
        "challengeへ署名",
        "選択されたCredential秘密鍵でauthenticatorDataとclientDataHashへ署名します。",
        "秘密鍵はAuthenticator外へ出ません。",
        "signature = sign(privateKey, authenticatorData || clientDataHash)",
      ),
      step(
        "auth",
        "client",
        "Assertionを返却",
        "credentialId、authenticatorData、clientDataJSON、signatureなどを返します。",
        "ブラウザスクリプトが受け取るのは署名結果であり秘密鍵ではありません。",
        "AuthenticatorAssertionResponse",
      ),
      step(
        "client",
        "api",
        "Assertionを送信",
        "ブラウザが署名結果をRelying PartyへHTTPSで送ります。",
        "認証応答をログや分析基盤へ不用意に記録しません。",
        "POST /webauthn/authentication/verify",
      ),
      step(
        "api",
        "api",
        "署名を検証",
        "保存済み公開鍵で署名、challenge、origin、RP ID hash、flags、counterを検証します。",
        "全検証成功後にのみアプリケーションセッションを発行します。",
        "verify(assertion, storedPublicKey) → session",
      ),
    ],
  }),
  protocol({
    slug: "fido-uaf",
    shortName: "FIDO UAF",
    title: "FIDO UAF Passwordless Authentication",
    eyebrow: "FIDO UAF 1.1 / Passwordless Authentication",
    summary:
      "端末内Authenticatorを使い、Relying Partyが指定するPolicyに適合した公開鍵Credentialでパスワードレス認証する従来FIDOフローです。",
    accent: "cyan",
    family: "OpenID Connect",
    status: "specialized",
    actors: fidoActors,
    highlights: [
      ["Model", "Passwordless"],
      ["Policy", "Authenticator matching"],
      ["Transport", "TLS required"],
    ],
    steps: [
      step(
        "user",
        "api",
        "UAF操作を開始",
        "ユーザーが登録または認証操作を開始します。",
        "すべてのUAFメッセージをTLSで保護します。",
        "POST /uaf/request",
      ),
      step(
        "api",
        "client",
        "UAF Requestを返却",
        "FIDO Serverがchallenge、AppID、許可Authenticator Policyを返します。",
        "challengeを推測不能かつ一回限りにします。",
        "UAF RegistrationRequest / AuthenticationRequest",
      ),
      step(
        "client",
        "auth",
        "Policy適合Authenticatorを呼ぶ",
        "UAF ClientがPolicyに一致するAuthenticatorを選択してASM経由で呼び出します。",
        "Facet IDとAppIDの関係を検証します。",
        "UAF Client → ASM → Authenticator",
      ),
      step(
        "auth",
        "user",
        "ローカル本人確認",
        "Authenticatorが生体認証やPINでユーザーを確認します。",
        "認証要素は端末内で処理しサーバーへ送信しません。",
        "Local user verification",
      ),
      step(
        "auth",
        "client",
        "署名Assertionを生成",
        "登録では鍵生成、認証ではchallengeへの署名を行いUAF Assertionを返します。",
        "鍵はAppID固有で、秘密鍵はAuthenticator内に残ります。",
        "TAG_UAFV1_REG_ASSERTION / AUTH_ASSERTION",
      ),
      step(
        "client",
        "api",
        "UAF Responseを送信",
        "UAF Clientが署名済み応答をFIDO Serverへ返します。",
        "改変されたSignedDataやKeyRegistrationDataは検証で拒否します。",
        "POST /uaf/response",
      ),
      step(
        "api",
        "api",
        "Assertionを検証",
        "FIDO ServerがPolicy、challenge、署名、counter、Authenticator Metadataを検証します。",
        "成功時のみCredential登録またはセッション発行を行います。",
        "verify(UAF assertion) → authenticated",
      ),
    ],
  }),
  protocol({
    slug: "fido-u2f",
    shortName: "FIDO U2F",
    title: "FIDO U2F Second-Factor Authentication",
    eyebrow: "FIDO U2F 1.2 / Universal Second Factor",
    summary:
      "パスワード認証にフィッシング耐性のあるSecurity Key操作を追加し、公開鍵署名で第二要素を証明する従来FIDOフローです。",
    accent: "cyan",
    family: "OpenID Connect",
    status: "legacy",
    actors: fidoActors,
    highlights: [
      ["Model", "Second factor"],
      ["Device", "Security key"],
      ["Successor", "FIDO2 / WebAuthn"],
    ],
    steps: [
      step(
        "user",
        "api",
        "第一要素でログイン",
        "ユーザー名とパスワードなどの第一要素を検証します。",
        "U2F単体はユーザー識別を置き換えず第二要素として使われます。",
        "POST /login  username + password",
      ),
      step(
        "api",
        "client",
        "U2F challengeを返却",
        "AppID、challenge、登録済みKey Handleをブラウザへ返します。",
        "challengeは一度だけ使用し、セッションと関連付けます。",
        "SignRequest { appId, challenge, keyHandle }",
      ),
      step(
        "client",
        "auth",
        "Security Keyへ署名要求",
        "ブラウザがUSB、NFC、BLEなどでU2F Authenticatorを呼び出します。",
        "AppIDと要求originの関係をクライアント側で確認します。",
        "U2F_AUTHENTICATE",
      ),
      step(
        "auth",
        "user",
        "タッチを要求",
        "Security Keyがユーザーの物理操作を確認します。",
        "User Presenceによりバックグラウンドでの無断認証を防ぎます。",
        "User presence test",
      ),
      step(
        "auth",
        "auth",
        "署名を生成",
        "AppID hash、user presence、counter、challenge hashへ秘密鍵で署名します。",
        "RPごとに異なる鍵を使用しCredentialの横断追跡を抑えます。",
        "ECDSA signature + counter",
      ),
      step(
        "auth",
        "client",
        "署名応答を返却",
        "Key Handle、署名、counterなどをブラウザへ返します。",
        "秘密鍵はSecurity Keyから出ません。",
        "SignResponse",
      ),
      step(
        "client",
        "api",
        "第二要素を検証",
        "サーバーが登録済み公開鍵で署名とcounterを検証します。",
        "新規実装では後継のWebAuthn/FIDO2を使用します。",
        "verify(signature, challenge, counter) → session",
      ),
    ],
  }),
];
