import "server-only";

import { Pool } from "pg";

export type AuthEventType =
  "LOGIN_STARTED" | "LOGIN_SUCCEEDED" | "LOGIN_DENIED" | "LOGIN_FAILED" | "LOGOUT";

export type AuthEvent = {
  id: string;
  eventType: AuthEventType;
  subject: string | null;
  detail: Record<string, unknown>;
  occurredAt: Date;
};

const pool = new Pool({
  connectionString:
    process.env.CLIENT_DB_URL ??
    "postgresql://auth_user:auth_password@localhost:5432/auth_services",
  max: 5,
});

let schemaReady: Promise<void> | undefined;

function ensureSchema() {
  schemaReady ??= (async () => {
    await pool.query("CREATE SCHEMA IF NOT EXISTS client_app");
    await pool.query(`
      CREATE TABLE IF NOT EXISTS client_app.auth_event (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        event_type varchar(40) NOT NULL,
        subject varchar(200),
        detail jsonb NOT NULL DEFAULT '{}'::jsonb,
        occurred_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `);
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_auth_event_subject_occurred_at
      ON client_app.auth_event (subject, occurred_at DESC)
    `);
  })();
  return schemaReady;
}

export async function recordAuthEvent(
  eventType: AuthEventType,
  subject: string | null,
  detail: Record<string, unknown> = {},
) {
  await ensureSchema();
  await pool.query(
    `
      INSERT INTO client_app.auth_event (event_type, subject, detail)
      VALUES ($1, $2, $3::jsonb)
    `,
    [eventType, subject, JSON.stringify(detail)],
  );
}

export async function recordAuthEventSafely(
  eventType: AuthEventType,
  subject: string | null,
  detail: Record<string, unknown> = {},
) {
  try {
    await recordAuthEvent(eventType, subject, detail);
  } catch (error) {
    console.error("Failed to persist auth audit event", { eventType, subject, error });
  }
}

export async function listRecentAuthEvents(subject: string, limit = 10): Promise<AuthEvent[]> {
  try {
    await ensureSchema();
    const result = await pool.query<AuthEvent>(
      `
        SELECT id::text AS "id",
               event_type AS "eventType",
               subject,
               detail,
               occurred_at AS "occurredAt"
        FROM client_app.auth_event
        WHERE subject = $1
        ORDER BY occurred_at DESC, id DESC
        LIMIT $2
      `,
      [subject, Math.min(Math.max(limit, 1), 50)],
    );
    return result.rows;
  } catch (error) {
    console.error("Failed to load auth audit events", { subject, error });
    return [];
  }
}
