CREATE TABLE demo_resource (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_subject varchar(200) NOT NULL,
    title varchar(200) NOT NULL,
    description varchar(1000) NOT NULL,
    status varchar(30) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_demo_resource_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_demo_resource_owner ON demo_resource (owner_subject, created_at DESC);

INSERT INTO demo_resource (owner_subject, title, description, status)
VALUES
    ('user', 'OAuth 2.1 protected resource', 'profile scopeで取得できるデモデータです。', 'ACTIVE'),
    ('user', 'Archived authorization note', 'JWTのsubで所有者を分離しています。', 'ARCHIVED');
