server:
  port: 8080

spring:
  datasource:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/auth_services?currentSchema=resource_server}
    username: ${RESOURCE_DB_USERNAME:auth_user}
    password: ${RESOURCE_DB_PASSWORD:auth_password}
  flyway:
    locations: classpath:db/migration
    schemas: resource_server
    default-schema: resource_server
    create-schemas: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_ISSUER:http://localhost:9000}
          jwk-set-uri: ${AUTHORIZATION_SERVER_JWK_SET_URI:http://localhost:9000/oauth2/jwks}

management:
  endpoints:
    web:
      exposure:
        include: health
