map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

error_log /dev/null crit;

server {
    listen 443 ssl;
    server_name authorization-server.local.gekal.cn;

    ssl_certificate /etc/nginx/certs/local.gekal.cn/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/local.gekal.cn/privkey.pem;
    access_log off;

    location / {
        proxy_pass http://authorization-server:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}

server {
    listen 443 ssl;
    server_name resource-server.local.gekal.cn;

    ssl_certificate /etc/nginx/certs/local.gekal.cn/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/local.gekal.cn/privkey.pem;
    access_log off;

    location / {
        proxy_pass http://resource-server:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Request-ID $request_id;
    }
}

server {
    listen 443 ssl;
    server_name client-app.local.gekal.cn;

    ssl_certificate /etc/nginx/certs/local.gekal.cn/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/local.gekal.cn/privkey.pem;
    access_log off;

    location / {
        proxy_pass http://client-app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
