server:
  port: 9000

spring:
  application:
    name: authorization-server
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_services?currentSchema=authorization_server}
    username: ${AUTH_DB_USERNAME:auth_user}
    password: ${AUTH_DB_PASSWORD:auth_password}
  flyway:
    locations: classpath:db/migration
    schemas: authorization_server
    default-schema: authorization_server
    create-schemas: true

logging:
  structured:
    format:
      console: ${LOGGING_STRUCTURED_FORMAT_CONSOLE:}
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
